name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Install Dependencies
        run: npm i
      - name: Check Solidity Compilation
        run: npm run sol:compile
      - name: Check Solidity Solhint
        run: npm run lint-solc
      - name: Check Eslint
        run: npm run lint
      - name: Build
        run: npm run build
      # TODO: fix css files throwing 404 errors
      - name: Check internal links
        run: npm run linkcheck-internal
      - name: Check types
        run: npm run typecheck